#!/bin/bash
#
# Show all the lines which are the target destination of a jump in BASIC.
# Handles GOTO, GOSUB, THEN.

# This is useful so that we can make sure that lines which are
# destinations do not get removed when we shrink the program by
# removing comments.

# This could be done more simply, but has added complexity because
# commas allowed for ON GOSUB and ON GOTO. Also, this program expanded
# to make the output more aestheticlly pleasing.
#
# hackerb9 2022 Sep 4


if [[ $1 == "-l" ]]; then LFLAG=true; shift; fi

file=${1:-M100LE+comments.DO}	# Default file to check if not specified 

cat "$file" |
    egrep -io '(GOTO|GOSUB|THEN|ELSE|RESTORE|)(\s*,?\s*[0-9]+)+' |
    sed -r 's/([A-Z,])([0-9]+)/\1 \2/gi;	      # Add " " in GOSUB4200 
    	    s/([^0-9])0+/\1/g' |	     	      # Remove leading zeroes
    tr ',' '\t' |				      # Commas become tabs
    while read jump alldestinations
    do
	set -- $alldestinations
	for destination; do
	    if ! [[ $LFLAG ]]; then 
		printf "%5s %5s\n" $jump $destination
	    else
		printf "%s\n" $destination
	    fi
	done
    done |
    sort -n -k1 | uniq | sort --stable -n -k2

