#line 2 "m100-tokenize.c"

#line 4 "m100-tokenize.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer tokenize_create_buffer
#define yy_delete_buffer tokenize_delete_buffer
#define yy_scan_buffer tokenize_scan_buffer
#define yy_scan_string tokenize_scan_string
#define yy_scan_bytes tokenize_scan_bytes
#define yy_init_buffer tokenize_init_buffer
#define yy_flush_buffer tokenize_flush_buffer
#define yy_load_buffer_state tokenize_load_buffer_state
#define yy_switch_to_buffer tokenize_switch_to_buffer
#define yypush_buffer_state tokenizepush_buffer_state
#define yypop_buffer_state tokenizepop_buffer_state
#define yyensure_buffer_stack tokenizeensure_buffer_stack
#define yy_flex_debug tokenize_flex_debug
#define yyin tokenizein
#define yyleng tokenizeleng
#define yylex tokenizelex
#define yylineno tokenizelineno
#define yyout tokenizeout
#define yyrestart tokenizerestart
#define yytext tokenizetext
#define yywrap tokenizewrap
#define yyalloc tokenizealloc
#define yyrealloc tokenizerealloc
#define yyfree tokenizefree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define tokenize_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer tokenize_create_buffer
#endif

#ifdef yy_delete_buffer
#define tokenize_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer tokenize_delete_buffer
#endif

#ifdef yy_scan_buffer
#define tokenize_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer tokenize_scan_buffer
#endif

#ifdef yy_scan_string
#define tokenize_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string tokenize_scan_string
#endif

#ifdef yy_scan_bytes
#define tokenize_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes tokenize_scan_bytes
#endif

#ifdef yy_init_buffer
#define tokenize_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer tokenize_init_buffer
#endif

#ifdef yy_flush_buffer
#define tokenize_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer tokenize_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define tokenize_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state tokenize_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define tokenize_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer tokenize_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define tokenizepush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state tokenizepush_buffer_state
#endif

#ifdef yypop_buffer_state
#define tokenizepop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state tokenizepop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define tokenizeensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack tokenizeensure_buffer_stack
#endif

#ifdef yylex
#define tokenizelex_ALREADY_DEFINED
#else
#define yylex tokenizelex
#endif

#ifdef yyrestart
#define tokenizerestart_ALREADY_DEFINED
#else
#define yyrestart tokenizerestart
#endif

#ifdef yylex_init
#define tokenizelex_init_ALREADY_DEFINED
#else
#define yylex_init tokenizelex_init
#endif

#ifdef yylex_init_extra
#define tokenizelex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra tokenizelex_init_extra
#endif

#ifdef yylex_destroy
#define tokenizelex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy tokenizelex_destroy
#endif

#ifdef yyget_debug
#define tokenizeget_debug_ALREADY_DEFINED
#else
#define yyget_debug tokenizeget_debug
#endif

#ifdef yyset_debug
#define tokenizeset_debug_ALREADY_DEFINED
#else
#define yyset_debug tokenizeset_debug
#endif

#ifdef yyget_extra
#define tokenizeget_extra_ALREADY_DEFINED
#else
#define yyget_extra tokenizeget_extra
#endif

#ifdef yyset_extra
#define tokenizeset_extra_ALREADY_DEFINED
#else
#define yyset_extra tokenizeset_extra
#endif

#ifdef yyget_in
#define tokenizeget_in_ALREADY_DEFINED
#else
#define yyget_in tokenizeget_in
#endif

#ifdef yyset_in
#define tokenizeset_in_ALREADY_DEFINED
#else
#define yyset_in tokenizeset_in
#endif

#ifdef yyget_out
#define tokenizeget_out_ALREADY_DEFINED
#else
#define yyget_out tokenizeget_out
#endif

#ifdef yyset_out
#define tokenizeset_out_ALREADY_DEFINED
#else
#define yyset_out tokenizeset_out
#endif

#ifdef yyget_leng
#define tokenizeget_leng_ALREADY_DEFINED
#else
#define yyget_leng tokenizeget_leng
#endif

#ifdef yyget_text
#define tokenizeget_text_ALREADY_DEFINED
#else
#define yyget_text tokenizeget_text
#endif

#ifdef yyget_lineno
#define tokenizeget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno tokenizeget_lineno
#endif

#ifdef yyset_lineno
#define tokenizeset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno tokenizeset_lineno
#endif

#ifdef yywrap
#define tokenizewrap_ALREADY_DEFINED
#else
#define yywrap tokenizewrap
#endif

#ifdef yyalloc
#define tokenizealloc_ALREADY_DEFINED
#else
#define yyalloc tokenizealloc
#endif

#ifdef yyrealloc
#define tokenizerealloc_ALREADY_DEFINED
#else
#define yyrealloc tokenizerealloc
#endif

#ifdef yyfree
#define tokenizefree_ALREADY_DEFINED
#else
#define yyfree tokenizefree
#endif

#ifdef yytext
#define tokenizetext_ALREADY_DEFINED
#else
#define yytext tokenizetext
#endif

#ifdef yyleng
#define tokenizeleng_ALREADY_DEFINED
#else
#define yyleng tokenizeleng
#endif

#ifdef yyin
#define tokenizein_ALREADY_DEFINED
#else
#define yyin tokenizein
#endif

#ifdef yyout
#define tokenizeout_ALREADY_DEFINED
#else
#define yyout tokenizeout
#endif

#ifdef yy_flex_debug
#define tokenize_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug tokenize_flex_debug
#endif

#ifdef yylineno
#define tokenizelineno_ALREADY_DEFINED
#else
#define yylineno tokenizelineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 134
#define YY_END_OF_BUFFER 135
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[363] =
    {   0,
        0,    0,    0,    0,    0,    0,  135,  134,    4,  134,
        2,  133,   88,   86,   87,   89,  100,   99,   98,   41,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,   97,   90,  134,    4,  134,    1,    3,    4,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   15,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       28,    0,   92,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   71,    0,    0,    0,    0,    0,    1,
        4,    1,  103,   91,  127,  115,    0,    0,    0,    0,
        0,    0,    0,   54,   51,    0,  112,    0,    0,    0,
        0,    0,   38,   10,    0,    0,    0,    5,  117,   94,
       74,   75,  111,    0,  123,    6,  104,    0,    0,    0,
        0,   95,    0,  105,    0,  102,   65,   53,    0,    0,
        0,  124,   12,    0,    0,    0,    0,    0,  118,  119,
      110,    0,    0,   61,   52,    0,    0,    0,   96,    0,

        0,   69,    0,   84,   81,    0,   27,    0,    0,  107,
        0,    0,    0,    0,    0,   19,    0,    0,    0,  109,
       14,    0,    0,  101,  113,    0,    0,  108,    0,    0,
        0,    0,  114,    0,    0,    0,  126,    0,    0,   93,
       55,   63,  122,  128,  120,    0,    0,    0,   42,    0,
      121,    0,    8,    0,   50,    0,    0,   24,   22,    0,
        0,    0,   13,    0,    0,    0,    0,   67,    0,    0,
        0,   23,   43,    0,   32,  106,    0,   64,    0,  132,
        0,   66,    7,   30,  116,   39,    0,    0,    0,   58,
       11,    0,    0,    0,    0,   35,    0,    0,    0,   85,

       20,  125,    0,   70,   83,    0,    0,    0,    0,   45,
       46,   31,   47,    0,   49,   78,   29,   25,   34,   17,
       82,    0,    9,   77,   57,  130,    0,   44,    0,   33,
       60,   62,    0,   40,    0,    0,    0,    0,    0,   56,
        0,    0,   48,   72,    0,   21,   80,   79,   36,   37,
       59,    0,   26,   18,  131,   68,  129,    0,   73,   16,
       76,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    7,    1,    8,    1,    1,    9,   10,
        1,   11,   12,    1,   13,    1,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,    1,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,    1,
        1,   44,    1,   45,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[364] =
    {   0,
        0,   44,   48,   49,   55,   58,  409,  410,  410,  405,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
       36,  383,   55,   42,   70,   36,  373,  377,   55,   43,
       91,   71,   57,   95,   74,   94,  115,   81,  367,  383,
      374,  368,  410,  410,  152,  157,  171,  117,  410,  410,
      363,  376,  376,  365,  372,  365,  373,  357,  360,  114,
      108,  110,  126,  366,  359,  360,  360,  350,  363,  360,
      344,  135,  349,   54,  346,  357,  164,  349,  410,  345,
      150,  348,  334,  346,  342,  153,  346,  157,  345,  170,
      147,  330,  340,  161,  347,  175,  338,  140,  330,  342,

      410,  342,  410,  327,  340,  170,  176,  339,  183,  336,
      338,  328,  319,  322,  325,  324,  316,  334,  317,  182,
       44,  328,  320,  410,  322,  180,  326,  312,  220,  202,
      225,  410,  410,  410,  410,  410,  313,  316,  315,  336,
      305,  322,  199,  410,  410,  303,  410,  300,  313,  308,
      185,  329,  410,  410,  204,  298,  311,  410,  410,  410,
      410,  301,  410,  309,  410,  410,  410,  232,  293,  298,
      306,  410,  305,  289,  289,  410,  410,  410,  296,  291,
      286,  410,  410,  293,  298,  283,  283,  296,  410,  410,
      410,  281,  289,  410,  410,  277,  289,  306,  410,  280,

      288,  410,  273,  410,  410,  278,  410,  280,  284,  410,
      283,  269,  273,  266,  280,  410,  203,  263,  274,  410,
      410,  276,  275,  410,  410,  266,  275,  410,  262,  261,
       89,  284,  410,  261,  268,  259,  410,  256,  251,  410,
      410,  410,  410,  410,  410,  252,  264,  262,  410,  261,
      410,  256,  410,  275,  410,  274,  273,  410,  410,  244,
      242,  257,  410,  246,  233,  237,  238,  410,  230,  264,
      247,  410,  410,  231,  410,  410,  236,  410,  243,  410,
      230,  410,  410,  410,  410,  410,  229,  240,  225,  410,
      410,  229,  230,  224,  221,  410,  234,  234,  232,  410,

      410,  410,  223,  410,  410,  246,  227,  214,  224,  410,
      410,  410,  410,  218,  410,  410,  410,  410,  410,  410,
      410,  241,  410,  410,  410,  410,  211,  410,  209,  410,
      410,  410,  208,  410,  209,  220,  211,  231,  201,  410,
      204,  142,  410,  410,  116,  410,  410,  410,  410,  410,
      410,  120,  410,  410,  410,  410,  410,  128,  410,  410,
      410,  410,  127
    } ;

static const flex_int16_t yy_def[364] =
    {   0,
      362,    1,  363,  363,  363,  363,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,    0,  362
    } ;

static const flex_int16_t yy_nxt[456] =
    {   0,
        8,    8,    9,    8,   10,    8,   11,    8,   12,    8,
       13,   14,   15,   16,    8,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,    8,   36,   37,   38,   39,   40,
       41,   42,    8,   43,   44,   45,   46,   45,   47,   45,
        9,    9,   10,   10,   49,   49,   51,    9,   48,   10,
        9,   63,   10,   74,  232,   64,   83,   52,   75,   65,
       84,   76,   53,   54,   56,  233,   97,   57,   66,   79,
       98,   58,   59,  164,   60,   80,   81,   61,   82,   99,
       92,   62,   67,   93,   94,  165,  302,  105,   95,   68,

      121,   69,   70,   96,   71,   72,  106,  122,  123,  107,
      108,   73,   85,  124,   86,   87,  303,  109,   88,  100,
       89,  110,  132,   90,   91,  111,  101,    8,  102,  148,
      103,  130,  112,  104,  113,  361,  114,  142,  145,  146,
      115,  149,  116,  360,  147,  150,  143,  117,  118,  119,
      144,  359,  120,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  151,  161,  168,  130,  358,  152,  168,
      162,  130,  129,  131,  129,  129,  129,  181,  173,  192,
      202,  203,  193,  174,  182,  130,  175,  176,  185,  188,
      183,  189,  196,  186,  190,  191,  197,  199,  209,  212,

      169,  170,  215,  213,  253,  229,  210,  132,  254,  237,
      211,  357,  200,  216,  230,  238,  130,  231,  247,  217,
      218,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  256,  356,  168,  130,  248,  257,  168,  355,  130,
      292,  293,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  170,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  301,  300,  299,  298,  297,  296,

      295,  294,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  255,  252,  251,  250,
      249,  246,  245,  244,  243,  242,  241,  240,  239,  236,
      235,  234,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  214,  208,  207,  206,  205,  204,  201,  198,
      195,  194,  187,  184,  180,  179,  178,  177,  172,  171,
      167,  166,  163,  160,  159,  158,  157,  156,  155,  154,
      153,  141,  140,  139,  138,  137,  136,  135,  134,  133,

      128,  127,  126,  125,   78,   77,   55,   50,  362,    7,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362
    } ;

static const flex_int16_t yy_chk[456] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        3,    4,    3,    4,    3,    4,   21,    5,    2,    5,
        6,   24,    6,   26,  121,   24,   30,   21,   26,   24,
       30,   26,   21,   21,   23,  121,   33,   23,   24,   29,
       33,   23,   23,   74,   23,   29,   29,   23,   29,   33,
       32,   23,   25,   32,   32,   74,  231,   35,   32,   25,

       38,   25,   25,   32,   25,   25,   35,   38,   38,   35,
       35,   25,   31,   38,   31,   31,  231,   36,   31,   34,
       31,   36,   48,   31,   31,   36,   34,  363,   34,   62,
       34,   48,   36,   34,   37,  358,   37,   60,   61,   61,
       37,   62,   37,  352,   61,   62,   60,   37,   37,   37,
       60,  345,   37,   45,   45,   45,   45,   45,   46,   46,
       46,   46,   46,   63,   72,   77,   45,  342,   63,   77,
       72,   46,   47,   47,   47,   47,   47,   86,   81,   91,
       98,   98,   91,   81,   86,   47,   81,   81,   88,   90,
       86,   90,   94,   88,   90,   90,   94,   96,  106,  107,

       77,   77,  109,  107,  151,  120,  106,  130,  151,  126,
      106,  341,   96,  109,  120,  126,  130,  120,  143,  109,
      109,  129,  129,  129,  129,  129,  131,  131,  131,  131,
      131,  155,  339,  168,  129,  143,  155,  168,  338,  131,
      217,  217,  337,  336,  335,  333,  329,  327,  322,  314,
      309,  308,  307,  306,  303,  299,  298,  297,  295,  294,
      293,  292,  289,  288,  287,  281,  279,  277,  274,  168,
      271,  270,  269,  267,  266,  265,  264,  262,  261,  260,
      257,  256,  254,  252,  250,  248,  247,  246,  239,  238,
      236,  235,  234,  232,  230,  229,  227,  226,  223,  222,

      219,  218,  215,  214,  213,  212,  211,  209,  208,  206,
      203,  201,  200,  198,  197,  196,  193,  192,  188,  187,
      186,  185,  184,  181,  180,  179,  175,  174,  173,  171,
      170,  169,  164,  162,  157,  156,  152,  150,  149,  148,
      146,  142,  141,  140,  139,  138,  137,  128,  127,  125,
      123,  122,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  108,  105,  104,  102,  100,   99,   97,   95,
       93,   92,   89,   87,   85,   84,   83,   82,   80,   78,
       76,   75,   73,   71,   70,   69,   68,   67,   66,   65,
       64,   59,   58,   57,   56,   55,   54,   53,   52,   51,

       42,   41,   40,   39,   28,   27,   22,   10,    7,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "m100-tokenize.lex"
/* m100-tokenize.lex		TRS-80 Model 100 BASIC tokenizer *
 *
 * Flex uses this to create lex.tokenize.c.
 * 
 * Compile with:   	flex m100-tokenize.lex
 *			gcc lex.tokenize.c
 */
/* Define states that simply copy text instead of lexing */  


#line 16 "m100-tokenize.lex"
  /* Functions defined in m100-tokenize-main.c */
  int yyput(uint8_t);		/* putchar, but for yyout instead of stdout. */
  uint8_t lastput=255;		/* last written character, for EOF without nl */
  int fixup_ptrs();		/* rewrite line pointers, if possible. */
  /* An array to store line pointers, to be fixed up at EOF */
  uint16_t ptr[65536];
  int nlines = 0;
#line 938 "m100-tokenize.c"

#define INITIAL 0
#define string 1
#define remark 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "m100-tokenize.lex"


#line 1163 "m100-tokenize.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 363 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 410 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 27 "m100-tokenize.lex"
{
    ptr[nlines++] = ftell(yyout);   /* Cache the location of the current line */
    yyput('*'); yyput('*');	    /* Dummy placeholder pointer to next line. */
    uint16_t linenum=atoi(yytext);  /* BASIC line number. */
    yyput(linenum & 0xFF);
    yyput(linenum >> 8);
  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "m100-tokenize.lex"
yyput('"'); BEGIN(string);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "m100-tokenize.lex"
yyput('"'); BEGIN(INITIAL);
	YY_BREAK
/* Newline matches <string> and <remark> start conditions. */
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 39 "m100-tokenize.lex"
yyput('\0'); BEGIN(INITIAL);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
case YY_STATE_EOF(remark):
#line 41 "m100-tokenize.lex"
{
    (lastput == '\0') || yyput('\0'); /* Handle EOF without preceding newline */
    fixup_ptrs();
    yyterminate();
  }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "m100-tokenize.lex"
yyput(128);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "m100-tokenize.lex"
yyput(129);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "m100-tokenize.lex"
yyput(130);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "m100-tokenize.lex"
yyput(131);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "m100-tokenize.lex"
yyput(132);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "m100-tokenize.lex"
yyput(133);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "m100-tokenize.lex"
yyput(134);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "m100-tokenize.lex"
yyput(135);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "m100-tokenize.lex"
yyput(136);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "m100-tokenize.lex"
yyput(137);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "m100-tokenize.lex"
yyput(138);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "m100-tokenize.lex"
yyput(139);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "m100-tokenize.lex"
yyput(140);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "m100-tokenize.lex"
yyput(141);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "m100-tokenize.lex"
yyput(142); BEGIN(remark);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "m100-tokenize.lex"
yyput(143);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "m100-tokenize.lex"
yyput(144);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "m100-tokenize.lex"
yyput(':'); yyput(145);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "m100-tokenize.lex"
yyput(146);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "m100-tokenize.lex"
yyput(147);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "m100-tokenize.lex"
yyput(148);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "m100-tokenize.lex"
yyput(149);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "m100-tokenize.lex"
yyput(150);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "m100-tokenize.lex"
yyput(151);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "m100-tokenize.lex"
yyput(152);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "m100-tokenize.lex"
yyput(153);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "m100-tokenize.lex"
yyput(154);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "m100-tokenize.lex"
yyput(155);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "m100-tokenize.lex"
yyput(156);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "m100-tokenize.lex"
yyput(157);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "m100-tokenize.lex"
yyput(158);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "m100-tokenize.lex"
yyput(159);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "m100-tokenize.lex"
yyput(160);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "m100-tokenize.lex"
yyput(161);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "m100-tokenize.lex"
yyput(162);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "m100-tokenize.lex"
yyput(163);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "m100-tokenize.lex"
yyput(163);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "m100-tokenize.lex"
yyput(164);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "m100-tokenize.lex"
yyput(165);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "m100-tokenize.lex"
yyput(166);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "m100-tokenize.lex"
yyput(167);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "m100-tokenize.lex"
yyput(168);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "m100-tokenize.lex"
yyput(169);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "m100-tokenize.lex"
yyput(170);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "m100-tokenize.lex"
yyput(171);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "m100-tokenize.lex"
yyput(172);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "m100-tokenize.lex"
yyput(173);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "m100-tokenize.lex"
yyput(174);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "m100-tokenize.lex"
yyput(175);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "m100-tokenize.lex"
yyput(176);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "m100-tokenize.lex"
yyput(177);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "m100-tokenize.lex"
yyput(178);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "m100-tokenize.lex"
yyput(179);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "m100-tokenize.lex"
yyput(180);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "m100-tokenize.lex"
yyput(181);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 "m100-tokenize.lex"
yyput(182);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 "m100-tokenize.lex"
yyput(183);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 "m100-tokenize.lex"
yyput(184);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 "m100-tokenize.lex"
yyput(185);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 106 "m100-tokenize.lex"
yyput(186);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 107 "m100-tokenize.lex"
yyput(187);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 108 "m100-tokenize.lex"
yyput(188);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "m100-tokenize.lex"
yyput(189);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "m100-tokenize.lex"
yyput(190);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "m100-tokenize.lex"
yyput(191);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 112 "m100-tokenize.lex"
yyput(192);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "m100-tokenize.lex"
yyput(193);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 114 "m100-tokenize.lex"
yyput(194);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "m100-tokenize.lex"
yyput(195);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 116 "m100-tokenize.lex"
yyput(196);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 117 "m100-tokenize.lex"
yyput(197);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 "m100-tokenize.lex"
yyput(198);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 119 "m100-tokenize.lex"
yyput(199);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 120 "m100-tokenize.lex"
yyput(200);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 121 "m100-tokenize.lex"
yyput(201);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 122 "m100-tokenize.lex"
yyput(202);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 123 "m100-tokenize.lex"
yyput(203);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 124 "m100-tokenize.lex"
yyput(204);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 125 "m100-tokenize.lex"
yyput(205);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 126 "m100-tokenize.lex"
yyput(206);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 127 "m100-tokenize.lex"
yyput(207);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 128 "m100-tokenize.lex"
yyput(208);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 129 "m100-tokenize.lex"
yyput(209);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 130 "m100-tokenize.lex"
yyput(210);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 131 "m100-tokenize.lex"
yyput(211);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 132 "m100-tokenize.lex"
yyput(212);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 133 "m100-tokenize.lex"
yyput(213);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 134 "m100-tokenize.lex"
yyput(214);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 135 "m100-tokenize.lex"
yyput(215);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 136 "m100-tokenize.lex"
yyput(216);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 137 "m100-tokenize.lex"
yyput(217);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 138 "m100-tokenize.lex"
yyput(218);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 139 "m100-tokenize.lex"
yyput(219);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 140 "m100-tokenize.lex"
yyput(220);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 141 "m100-tokenize.lex"
yyput(221);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 142 "m100-tokenize.lex"
yyput(222);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 143 "m100-tokenize.lex"
yyput(223);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 144 "m100-tokenize.lex"
yyput(224);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 145 "m100-tokenize.lex"
yyput(225);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 146 "m100-tokenize.lex"
yyput(226);
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 147 "m100-tokenize.lex"
yyput(227);
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 148 "m100-tokenize.lex"
yyput(228);
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 149 "m100-tokenize.lex"
yyput(229);
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 150 "m100-tokenize.lex"
yyput(230);
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 151 "m100-tokenize.lex"
yyput(231);
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 152 "m100-tokenize.lex"
yyput(232);
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 153 "m100-tokenize.lex"
yyput(233);
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 154 "m100-tokenize.lex"
yyput(234);
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 155 "m100-tokenize.lex"
yyput(235);
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 156 "m100-tokenize.lex"
yyput(236);
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 157 "m100-tokenize.lex"
yyput(237);
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 158 "m100-tokenize.lex"
yyput(238);
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 159 "m100-tokenize.lex"
yyput(239);
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 160 "m100-tokenize.lex"
yyput(240);
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 161 "m100-tokenize.lex"
yyput(241);
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 162 "m100-tokenize.lex"
yyput(242);
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 163 "m100-tokenize.lex"
yyput(243);
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 164 "m100-tokenize.lex"
yyput(244);
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 165 "m100-tokenize.lex"
yyput(245);
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 166 "m100-tokenize.lex"
yyput(246);
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 167 "m100-tokenize.lex"
yyput(247);
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 168 "m100-tokenize.lex"
yyput(248);
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 169 "m100-tokenize.lex"
yyput(249);
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 170 "m100-tokenize.lex"
yyput(250);
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 171 "m100-tokenize.lex"
yyput(251);
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 172 "m100-tokenize.lex"
yyput(252);
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 173 "m100-tokenize.lex"
yyput(253);
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 174 "m100-tokenize.lex"
yyput(254);
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 175 "m100-tokenize.lex"
yyput(':'); yyput(0x8E); yyput(0xFF); BEGIN(remark);
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 177 "m100-tokenize.lex"
ECHO;
	YY_BREAK
#line 1910 "m100-tokenize.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 363 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 363 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 362);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 177 "m100-tokenize.lex"


/* The main() routine, yyput(), fixup_ptrs() */
    #include "m100-tokenize-main.c"

